###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 39
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:  
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#introduction:

###################################################
#                                                 #
#                     Panel                       #
#                                                 #
###################################################

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: !secret influxdb_url

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker: debug

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret api_password
  max_retries: 3
  default_measurement: state

####################################################
#                                                  #
#                      Cloud                       #
#                                                  #
####################################################

api:

alexa:

  smart_home:
    filter:
      include_entities:
        - light.luz_gateway # Alexa, enciende/apaga la luz del gateway
        - switch.bola_comedor # Alexa, enciende/apaga la bola del comedor
        - switch.cono_comedor # Alexa, enciende/apaga el cono del comedor
        - switch.arbol_navidad # Alexa, enciende/apaga el árbol de navidad
        - switch.leds_cocina # Alexa enciende/apaga los leds de la cocina
        - switch.bola_salita # Alexa, enciende/apaga la bola de la salita
        - switch.lampara_pie_salita # Alexa, enciende/apaga la lampara de pie de la salita
        - sensor.temperatura_dormitorio # Alexa, dime la temperatura del dormitorio
        - script.turn_on_livingroom_ambient_lights # Alexa, enciende las luces de ambiente del comedor
        - script.turn_off_livingroom_lights
        - script.turn_on_gamesroom_ambient_lights
      # include_domains:
      #   - switch
      exclude_entities:
      exclude_domains:
        - automation
        - climate
        - script
        - scene
        - sensor
        - input_boolean
        - media_player
        - switch
        - group
    entity_config:
      sensor.temperatura_dormitorio:
        name: Dormitorio
        
  flash_briefings:
    whoishome:
      - title: Quién está en casa?
        text: >
          {{ states.sensor.summary.state }}

intent_script:
  LucesEncendidasIntent:
    speech:
      text: >
        {{ states.sensor.lights_summary.state }}
  CalefaccionIntent:
    speech:
      text: >
        {{ states.sensor.heating_summary.state }}

#alexa:
#  intents:
#  # OCTOPRINT STATUS
#  PrinterStatusIntent:
#    speech:
#      type: plaintext
#      text: >
#        The printer is {{ states("sensor.octoprint_current_state") | lower }}
#        {% if is_state("binary_sensor.octoprint_printing", "on") %}
#          and the job is {{ states("sensor.octoprint_job_percentage") | round }} percent complete
#        {% else %}
#          and not currently printing
#        {% endif %}.

# intent_script:
#   ActivateSceneIntent:
#     action:
#       service: script.turn_on
#       data_template:
#         entity_id: script.{{ Scene | replace(" ", "_") }}
#     speech:
#       type: plain
#       text: OK

#emulated_hue:

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

####################################################
#                                                  #
#                    Components                    #
#                                                  #
####################################################

# Example configuration.yaml entry
weather:
  - platform: darksky
    api_key: !secret darksky_apikey
    latitude: !secret latitude
    longitude: !secret longitude

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: TelegramDePablo
    platform: telegram
    chat_id: !secret telegram_chat_id

# Vacuum
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token

# IFTTT
ifttt:
  key: !secret ifttt_key

# Tuya components (Enchufes Teckin)
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 34
  platform: 'tuya'

# Xiaomi Gateways
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_1_key
      mac: !secret xiaomi_gateway_1_mac
      host: !secret xiaomi_gateway_1_ip

## Plex
# media_player:
#   - platform: plex
#     entity_namespace: 'plex'
#     include_non_clients: true
#     scan_interval: 5
#     show_all_controls: false
#     use_custom_entity_ids: true
#     use_episode_art: true
#     remove_unavailable_clients: true
#     client_remove_interval: 600

# # Google Assistant
# google_assistant:
#   project_id: !secret google_assistant_projectid
#   api_key: !secret google_assistant_apikey
#   exposed_domains:
#     - media_player
#     - light
#     - climate

####################################################
#                                                  #
#                       MQTT                       #
#                                                  #
####################################################

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

####################################################
#                                                  #
#              Custom components                   #
#                                                  #
####################################################

# setracker:
# remotetv

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

automation: !include_dir_merge_list automations
#device_tracker: !include_dir_list device_tracker/
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
group: !include groups.yaml
script: !include_dir_named scripts/
scene: !include_dir_list scenes/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
zone: !include zones.yaml