###################################################
#                                                 #
#         Lovelace UI Configuration File          #
#                                                 #
###################################################

resources:
  - url: /local/custom_ui/mini-media-player.js?v=0.8.7
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.0.8
    type: js
  - url: /local/custom_ui/button-card.js
    type: module
  - url: /local/custom_ui/slider-entity-row.js
    type: module
  - url: /local/custom_ui/simple-thermostat/simple-thermostat.js
    type: module
  - url: /local/custom_ui/monster-card/monster-card.js
    type: module
  - url: /local/custom_ui/group-card/group-card.js
    type: module
title: Smart Home
views:

####################################################
#                                                  #
#                    General                       #
#                                                  #
####################################################

- id: summary
  title: General
  icon: mdi:home
  # badges:
  #     - sun.sun
  #     - sensor.yr_symbol
  cards:
            
    - type: vertical-stack
      cards:
        - type: horizontal-stack
          cards:
            - type: gauge
              title: Exterior
              unit: '%'
              entity: sensor.dark_sky_temperature
              min: 0
              max: 44
              severity:
                green: 0
                yellow: 14
                red: 26
            - type: gauge
              title: Comedor
              unit: '%'
              entity: sensor.nest_thermostat_temperature
              min: 0
              max: 44
              severity:
                green: 0
                yellow: 20
                red: 23
        - type: horizontal-stack
          cards:
            - type: gauge
              title: Alma
              unit: '%'
              entity: sensor.temperatura_alma
              min: 0
              max: 44
              severity:
                green: 0
                yellow: 20
                red: 23
            - type: gauge
              title: Dormitorio
              unit: '%'
              entity: sensor.temperatura_dormitorio
              min: 0
              max: 44
              severity:
                green: 0
                yellow: 20
                red: 23
    
    - type: vertical-stack
      title: main_scripts
      cards:
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              icon: mdi:lightbulb
              entity: script.welcome_home
              name: Encender luces
              size: 40px
              color_type: card
              color: rgb(223, 255, 97)
              style:
                - text-transform: none
                - color: white
                - background-color: rgb(38, 174, 96)
            - type: "custom:button-card"
              icon: mdi:weather-sunny
              entity: script.wakeup_time
              name: Buenos días
              size: 40px
              color_type: card
              color: rgb(223, 255, 97)
              style:
                - text-transform: none
                - color: white
                - background-color: rgb(38, 174, 96)
            - type: "custom:button-card"
              icon: mdi:power
              entity: script.home_away
              name: Apagar luces
              size: 40px
              color_type: card
              color: rgb(223, 255, 97)
              style:
                - text-transform: none
                - color: white
                - background-color: rgb(28, 128, 199)
            - type: "custom:button-card"
              icon: mdi:sleep
              entity: script.bed_time
              name: Buenas noches
              size: 40px
              color_type: card
              color: rgb(223, 255, 97)
              style:
                - text-transform: none
                - color: white
                - background-color: rgb(28, 128, 199)
    
    # Thermostat
    - type: thermostat
      entity: climate.nest
    # - type: custom:simple-thermostat
    #   entity: climate.nest
    #   step_size: 0.5
    
    # Parkings
    - type: vertical-stack
      cards:
        - type: picture-glance
          title: Seat León
          entities:
            - camera.parking_seat_leon
          camera_image: camera.parking_seat_leon
          
    # Vacuum
    - type: vertical-stack
      cards:
        - type: picture-elements
          title: Limpieza
          image: '/local/images/vacuum_card.jpeg'
          elements:
            - type: icon
              icon: mdi:bell-ring
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.locate
              style:
                top: 90%
                left: 80%
                color: '#42445C'
            - type: icon
              icon: mdi:crosshairs
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.clean_spot
              style:
                top: 90%
                left: 65%
                color: '#42445C'
            - type: icon
              tap_action: call-service
              icon: mdi:home
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.return_to_base
              style:
                top: 90%
                left: 50%
                color: '#42445C'
            - type: icon
              icon: mdi:stop
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.stop
              style:
                top: 90%
                left: 35%
                color: '#42445C'
            - type: icon
              icon: mdi:play
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.start
              style:
                top: 90%
                left: 20%
                color: '#42445C'
             
    # # Weather   
    # - type: iframe
    #   url: https://embed.windy.com/embed2.html
    #   aspect_ratio: 75%  
      
    # - type: custom:monster-card
    #   card:
    #     type: entities
    #     title: Monster
    #   filter:
    #     include:
    #       - domain: device_tracker
    #         attributes:
    #           battery: '< 100'

####################################################
#                                                  #
#                     Luces                        #
#                                                  #
####################################################

- id: lights
  title: Luces
  icon: mdi:lightbulb
  cards:
    
    - type: custom:monster-card
      show_empty: false
      card:
        type: entities
        title: Luces encendidas
      filter:
        include:
          - domain: switch
            state: 'on'
          - domain: light
            state: 'on'
    
    - type: custom:group-card
      card:
        type: entities
        title: Comedor
      group: group.luces_comedor
    
    - type: custom:group-card
      card:
        type: entities
        title: Cocina
      group: group.luces_cocina

    - type: custom:group-card
      card:
        type: entities
        title: Despacho
      group: group.luces_despacho
          
    - type: custom:group-card
      card:
        type: entities
        title: Salita
      group: group.luces_salita
          
    - type: vertical-stack
      cards:
        - type: entities
          title: Aseo
          show_header_toggle: true
          entities:
            - type: custom:slider-entity-row
              entity: light.luz_gateway
        - type: sensor
          entity: sensor.iluminacion_gateaway
          name: Iluminación Gateway

####################################################
#                                                  #
#                 Media Players                    #
#                                                  #
####################################################

- id: media_players
  title: Media players
  icon: mdi:cast
  cards:
    
    - type: custom:mini-media-player
      entity: media_player.comedor
      name: Chromecast Comedor
      artwork: cover
      power_color: true
      hide_volume: true
      show_progress: true
    
    - type: custom:mini-media-player
      entity: media_player.salita
      name: Chromecast Salita
      artwork: cover
      power_color: true
      hide_volume: true
      show_progress: true
    
    - type: custom:mini-media-player
      entity: media_player.dormitorio
      name: Chromecast Dormitorio
      artwork: cover
      power_color: true
      hide_volume: true
      show_progress: true
      
    - type: custom:mini-media-player
      entity: media_player.echo_dot_comedor
      name: Echo Dot Comedor
      artwork: cover
      power_color: true
      hide_volume: true
      show_progress: true
      # media_buttons:
      #   - name: Ambient
      #     type: playlist
      #     url: spotify:user:ppalomo:playlist:1mUt7acwzTodWEK0jJ1r81
      
    - type: custom:mini-media-player
      entity: media_player.echo_dot_salita
      name: Echo Dot Salita
      artwork: cover
      power_color: true
      hide_volume: true
      show_progress: true
      
####################################################
#                                                  #
#                     Settings                     #
#                                                  #
####################################################

- id: settings  # Automatically created id
  title: Preferencias
  icon: mdi:settings
  cards:
  
    # Notifications
    - id: notifications
      type: entities
      title: Notificaciones
      icon: mdi:radar
      show_header_toggle: true
      entities:
        - input_boolean.notify_presence
        - input_boolean.notify_thermostat
        - input_boolean.notify_vacuum
        - input_boolean.notify_weather

    # Automations
    - id: automations
      type: entities
      title: Automatizaciones
      show_header_toggle: true
      entities:
        - entity: input_boolean.gateway_light_night_mode
        - entity: input_boolean.daily_vacuum
          name: Limpieza diaria
          icon: mdi:broom
