###################################################
#                                                 #
#         Lovelace UI Configuration File          #
#                                                 #
###################################################

resources:
  - url: /local/custom_ui/mini-media-player.js?v=0.8.7
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.0.8
    type: js
  - url: /local/custom_ui/button-card.js
    type: module
title: Smart Home
views:

####################################################
#                                                  #
#                    Inicio                        #
#                                                  #
####################################################

  - id: summary
    title: General
    icon: mdi:home
    cards:
    
    - type: weather-forecast
      entity: weather.dark_sky
      
    - type: entities
      title: Media Players
      entities:
       - entity: media_player.comedor
         type: custom:mini-media-player
         group: true
         icon: mdi:cast-connected
         artwork_border: true
         show_source: true
       - entity: media_player.salita
         type: custom:mini-media-player
         group: true
         icon: mdi:cast-connected
         artwork_border: true
         show_source: true
       - entity: media_player.dormitorio
         type: custom:mini-media-player
         group: true
         icon: mdi:cast-connected
         artwork_border: true
         show_source: true
    
    - type: "custom:mini-graph-card"
      entity: sensor.dark_sky_temperature
      height: 80
      line_width: 4
      font_size: 75
      labels: true
      detail: 2
      color: '#3498db'

    - type: "custom:mini-graph-card"
      entity: sensor.dark_sky_precip_intensity
      height: 80
      line_width: 4
      font_size: 75
      labels: true
      detail: 2
      color: '#3498db'

    # Vacuum
    - type: vertical-stack
      cards:
        - type: picture-elements
          title: Limpieza
          image: '/local/images/vacuum_card.jpeg'
          elements:
            - type: icon
              icon: mdi:bell-ring
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.locate
              style:
                top: 90%
                left: 80%
                color: '#3090C7'
            - type: icon
              icon: mdi:crosshairs
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.clean_spot
              style:
                top: 90%
                left: 65%
                color: '#3090C7'
            - type: icon
              tap_action: call-service
              icon: mdi:home
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.return_to_base
              style:
                top: 90%
                left: 50%
                color: '#3090C7'
            - type: icon
              icon: mdi:stop
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.stop
              style:
                top: 90%
                left: 35%
                color: '#3090C7'
            - type: icon
              icon: mdi:play
              tap_action: call-service
              entity: vacuum.xiaomi_vacuum_cleaner
              service: vacuum.start
              style:
                top: 90%
                left: 20%
                color: '#3090C7'
            - type: state-label
              tap_action: more-info
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
               top: 14%
               right: 38%
               color: rgb(255, 255, 255)
               transform: translate(0%,-50%)
               font-family: Trebuchet MS
               font-size: 150%
               font-weight: bold
               border-color: rgb(34, 154, 210)
               border-radius: 6px
               background-color: '#cccccc'
            - type: state-label
              entity: sensor.vacuum_cleanmainbrush
              style:
                top: 35%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleansidebrush
              style:
                top: 45%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleanfilter
              style:
                top: 55%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_sensordirtyleft
              style:
                top: 65%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_status
              style:
                top: 40%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: '#3090C7'
            - type: state-label
              entity: sensor.vacuum_battery
              style:
                top: 50%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_fan_speed
              style:
                top: 60%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleaned_area
              prefix: "Area:"
              style:
                top: 79%
                left: 31%
                color: '#84a6ba'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
            - type: state-label
              entity: sensor.vacuum_cleaning_time
              prefix: "Time:"
              style:
                top: 79%
                left: 51%
                color: '#84a6ba'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
        - type: "custom:button-card"
          action: script.vacuum_all
          color_type: label-card
          color: rgb(44, 109, 214)
          name: General
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              action: script.vacuum_kitchen
              color_type: card
              color: rgb(66, 134, 244)
              name: Cocina
            - type: "custom:button-card"
              action: script.vacuum_livingroom
              color_type: card
              color: rgb(66, 134, 244)
              name: Comedor
            - type: "custom:button-card"
              action: script.vacuum_kitchen
              color_type: card
              color: rgb(66, 134, 244)
              name: Despacho
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              action: script.vacuum_kitchen
              color_type: card
              color: rgb(66, 134, 244)
              name: Alma
            - type: "custom:button-card"
              action: script.vacuum_livingroom
              color_type: card
              color: rgb(66, 134, 244)
              name: Salita
            - type: "custom:button-card"
              action: script.vacuum_kitchen
              color_type: card
              color: rgb(66, 134, 244)
              name: Dormitorio
        - type: entities
          show_header_toggle: false
          entities:
            - input_boolean.notify_vacuum
            - input_boolean.daily_vacuum

####################################################
#                                                  #
#                     Comedor                      #
#                                                  #
####################################################

  - id: comedor
    title: Comedor
    #icon: mdi:lightbulb
    cards:
      
      # - type: entities
      #   title: Comedor
      #   entities:
          
      - type: glance
        entities:
          - entity: sensor.nest_thermostat_temperature
            name: Temperatura
          - entity: sensor.nest_thermostat_humidity
            name: Humedad
      
      - type: vertical-stack
        title: Luces
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:lightbulb
                entity: switch.bola_comedor
                name: Sofá
                color: rgb(255, 204, 97)
              - type: "custom:button-card"
                entity: switch.bola_comedor
                icon: mdi:lightbulb
                name: Bola
                color: rgb(255, 204, 97)
              - type: "custom:button-card"
                entity: switch.cono_comedor
                icon: mdi:lightbulb
                name: Cono
                color: rgb(255, 204, 97)
              - type: "custom:button-card"
                entity: switch.arbol_navidad
                icon: mdi:pine-tree
                name: Árbol
                color: rgb(38, 174, 96)
                
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            icon: mdi:weather-night
            entity: script.turn_on_livingroom_ambient_lights
            size: 40px
            name: Luces ambiente
            style:
              - text-transform: none
              - color: white
              - background-color: rgb(28, 128, 199)
          - type: "custom:button-card"
            icon: mdi:flash-off
            entity: script.turn_off_livingroom_lights
            name: Apagar luces
            size: 40px
            style:
              - text-transform: none
              - color: white
              - background-color: rgb(28, 128, 199)
                
    
      # # Iluminación Gateway
      # - type: sensor
      #   entity: sensor.iluminacion_gateaway
      #   name: Iluminación Gateway
      #   height: 75
      #   line_color: "#3498db"

####################################################
#                                                  #
#                    Dormitorio                    #
#                                                  #
####################################################

  - id: dormitorio
    title: Dormitorio
    #icon: mdi:lightbulb
    cards:
      
      - type: glance
        entities:
          - entity: sensor.temperatura_dormitorio
            name: Temperatura
          - entity: sensor.humedad_dormitorio
            name: Humedad
          - entity: sensor.presion_dormitorio
            name: Presión

####################################################
#                                                  #
#                     Cocina                       #
#                                                  #
####################################################

  - id: cocina
    title: Cocina
    cards:

      - type: vertical-stack
        title: Luces
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:lightbulb
                entity: switch.leds_cocina
                name: Leds TV
                color: rgb(255, 204, 97)

####################################################
#                                                  #
#                    Settings                      #
#                                                  #
####################################################

  - id: settings  # Automatically created id
    title: Preferencias
    icon: mdi:settings
    cards:
    
      # Notifications
      - id: notifications
        type: entities
        title: Notificaciones
        icon: mdi:radar
        show_header_toggle: true
        entities:
          - input_boolean.notify_presence
          - input_boolean.notify_thermostat
          - input_boolean.notify_vacuum
          - input_boolean.notify_weather

      # Automations
      - id: automations
        type: entities
        title: Automatizaciones
        show_header_toggle: true
        entities:
          - entity: input_boolean.gateway_light_night_mode
          - entity: input_boolean.daily_vacuum
            name: Limpieza diaria
            icon: mdi:broom

