###################################################
#                                                 #
#         Lovelace UI Configuration File          #
#                                                 #
###################################################

resources:
  - url: /local/custom_ui/mini-media-player.js?v=0.8.7
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.0.8
    type: js
  - url: /local/custom_ui/button-card.js
    type: module
  - url: /local/custom_ui/slider-entity-row.js
    type: module
title: Smart Home
views:

####################################################
#                                                  #
#                    General                       #
#                                                  #
####################################################

- id: summary
  title: General
  icon: mdi:home
  cards:

    - type: "custom:button-card"
      action: script.vacuum_kitchen
      color_type: card
      color: rgb(66, 134, 244)
      name: Alma

    - type: entities
      title: Entities card sample
      show_header_toggle: true
      entities:
        - type: call-service
          icon: mdi:power
          name: Bed light
          action_name: Toggle light
          service: light.toggle
          service_data:
            entity_id: light.bed_light
        - type: section
          label: Muahaha
        - type: weblink
          name: Home Assistant
          url: https://www.home-assistant.io/
          icon: mdi:home-assistant

####################################################
#                                                  #
#                     Luces                        #
#                                                  #
####################################################

- id: lights
  title: Luces
  icon: mdi:lightbulb
  cards:

    - type: entities
      title: Comedor
      show_header_toggle: true
      entities:
        - entity: switch.bola_comedor
        - entity: switch.cono_comedor
        - entity: switch.arbol_navidad
        - type: section
          label: Escenas
        - entity: script.turn_on_livingroom_ambient_lights
          icon: mdi:lightbulb
        - entity: script.turn_off_livingroom_lights
          icon: mdi:lightbulb-outline
    
    - type: entities
      title: Cocina
      show_header_toggle: true
      entities:
        - entity: switch.leds_cocina
        - type: section
          label: Escenas
        - entity: script.turn_on_kitchen_ambient_lights
          icon: mdi:lightbulb
        - entity: script.turn_off_kitchen_lights
          icon: mdi:lightbulb-outline
          
    - type: entities
      title: Despacho
      show_header_toggle: true
      entities:
        - entity: switch.sonoff02
        - type: section
          label: Escenas
        - entity: script.turn_on_office_ambient_lights
          icon: mdi:lightbulb
        - entity: script.turn_off_office_lights
          icon: mdi:lightbulb-outline
          
    - type: entities
      title: Salita
      show_header_toggle: true
      entities:
        - entity: switch.lampara_pie_salita
        - entity: switch.bola_salita
        - type: section
          label: Escenas
        - entity: script.turn_on_gamesroom_ambient_lights
          icon: mdi:lightbulb
        - entity: script.turn_off_gamesroom_lights
          icon: mdi:lightbulb-outline
          
    - type: entities
      title: Aseo
      show_header_toggle: true
      entities:
        - type: custom:slider-entity-row
          entity: light.luz_gateway

    
# # This file was automatically generated by lovelace_migrate.py
# # https://github.com/dale3h/python-lovelace

# title: Home
# views:
#   - title: Home
#     cards:
#       - type: entities
#         title: Luces del comedor
#         show_header_toggle: true
#         entities:
#           - switch.cono_comedor
#           - switch.arbol_navidad
#           - switch.bola_comedor
#       - type: entities
#         title: Luces de la cocina
#         show_header_toggle: true
#         entities:
#           - switch.leds_cocina
#       - type: media-control
#         entity: media_player.comedor
#       - type: entities
#         title: all switches
#         show_header_toggle: true
#         entities:
#           - switch.cono_comedor
#           - switch.lampara_pie_salita
#           - switch.power_tv_comedor
#           - switch.63804520600194a91ffc_2
#           - switch.06712363840d8e49683f_3
#           - switch.63804520600194a91ffc_3
#           - switch.bola_comedor
#           - switch.bola_salita
#           - switch.06712363840d8e49683f_7
#           - switch.usb_salita
#           - switch.leds_cocina
#           - switch.arbol_navidad
#           - switch.tv_comedor
#           - switch.tv_comedor_volumen
#           - switch.sonoff01
#           - switch.sonoff02
#           - switch.sonoff02_2
#       - type: entities
#         title: all scripts
#         show_header_toggle: true
#         entities:
#           - script.heating_set_mode_off
#           - script.turn_off_kitchen_lights
#           - script.turn_off_livingroom_lights
#           - script.turn_off_office_lights
#           - script.turn_off_gamesroom_lights
#           - script.bed_time
#           - script.wakeup_time
#           - script.wakeup_time_tv_on
#           - script.vacuum_livingroom
#           - script.vacuum_all
#           - script.vacuum_kitchen
#           - script.turn_on_kitchen_ambient_lights
#           - script.turn_on_gamesroom_ambient_lights
#           - script.turn_on_livingroom_ambient_lights
#           - script.tv_time
#           - script.home_away
#           - script.set_heating_temperature_20
#           - script.set_heating_temperature_21
#           - script.set_heating_temperature_22
#           - script.set_heating_temperature_23
#           - script.set_heating_temperature_24
#           - script.set_heating_temperature_25
#           - script.heating_set_mode_eco
#       - type: entities
#         title: all automations
#         show_header_toggle: true
#         entities:
#           - automation.alerta_de_lluvia
#           - automation.alguien_ha_llegado_a_casa
#           - automation.apagado_automatico_de_luces
#           - automation.bla_bla_bla
#           - automation.el_termostato_esta_apagado
#           - automation.el_termostato_esta_en_modo_eco
#           - automation.encendido_automatico_de_la_luz_del_gateway
#           - automation.encendido_automatico_de_luces_del_comedor
#           - automation.ifttt_test
#           - automation.la_calefaccion_se_ha_encendido
#           - automation.la_limpieza_ha_finalizado
#       - type: entities
#         title: all lights
#         show_header_toggle: true
#         entities:
#           - light.luz_gateway
#       - type: entities
#         title: all vacuum cleaners
#         show_header_toggle: true
#         entities:
#           - vacuum.xiaomi_vacuum_cleaner
#       - type: entities
#         title: calendar
#         show_header_toggle: true
#         entities:
#           - calendar.aniversarios
#           - calendar.compartido
#           - calendar.festivos
#           - calendar.pablo_palomo
#       - type: media-control
#         entity: media_player.comedor
#       - type: media-control
#         entity: media_player.echo_dot
#       - type: media-control
#         entity: media_player.firealma
#       - type: media-control
#         entity: media_player.pablos_echosim_beta
#       - type: media-control
#         entity: media_player.this_device
#       - type: media-control
#         entity: media_player.pablos_alexa_apps
#       - type: weather-forecast
#         entity: weather.dark_sky