###################################################
#                                                 #
#            Detección de presencia            #
#                                                 #
###################################################

- alias: Detección de presencia

  trigger:
    
    - platform: state
      entity_id: device_tracker.natalia, device_tracker.pablo
      from: not_home
      to: home
      
    - platform: state
      entity_id: device_tracker.natalia, device_tracker.pablo
      from: home
      to: not_home

  condition:
    
    - condition: state
      entity_id: input_boolean.notify_presence
      state: 'on'
      
    - condition: template
      value_template: '{{ ((as_timestamp(now()) -as_timestamp(states.binary_sensor.puerta_entrada.last_updated)) / 60 | int) < 10  }}'
  
  action:
    
    - service: notify.telegramdepablo
      data_template:
        title: "Detección de presencia:"
        message: >
          {% if trigger.entity_id == 'device_tracker.natalia' %}
            {% if is_state(trigger.entity_id, 'home') %}
              {{ "Natalia ha llegado a casa" }}
            {% else %}
              {{ "Natalia ha salido de casa" }}
            {% endif %}
          {% elif trigger.entity_id == 'device_tracker.pablo' %}
            {% if is_state(trigger.entity_id, 'home') %}
              {{ "Pablo ha llegado a casa" }}
            {% else %}
              {{ "Pablo ha salido de casa" }}
            {% endif %}
          {% endif %}
          - Tiempo desde apertura puerta: {{ ((as_timestamp(now()) -as_timestamp(states.binary_sensor.puerta_entrada.last_updated)) / 60) | round(2) }} min
