- platform: template
  sensors:
    nest_mode_eco:
      value_template: >-
        {% if is_state('sensor.nest_thermostat_operation_mode', 'eco') %}
          on
        {% else %}
          off
        {% endif %}