###################################################
#                                                 #
#                    IFTTT test                   #
#                                                 #
###################################################

- alias: IFTTT test

  trigger:
  
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
  
  action:
  
    service: notify.telegramdepablo
    data:
      title: "Termostato:"
      message: "IFTTT test"
    # - service_template: '{{ trigger.event.data.service }}'
    #   data_template:
    #     entity_id: '{{ trigger.event.data.entity_id }}'