- alias: Nest is heating mode

  trigger:
    - platform: state
      entity_id: sensor.nest_thermostat_operation_mode
      to: 'heat'

  condition:
    condition: state
    entity_id: input_boolean.notify_thermostat
    state: 'on'
  
  action:
    - service: notify.telegramdepablo
      data:
        title: "Termostato:"
        message: |
          Se ha encendido la calefacci처n
          - Temperatura actual: {{ states.sensor.nest_thermostat_temperature.state }}째C
          - Temperatura objetivo: {{ states.sensor.nest_thermostat_target.state }}째C
          - Temperatura exterior: {{ states.sensor.dark_sky_temperature.state }}째C