- alias: Nest is eco mode

  trigger:
    - platform: state
      entity_id: sensor.nest_thermostat_operation_mode
      to: 'eco'

  condition:
    condition: state
    entity_id: input_boolean.notify_thermostat
    state: 'on'

  action:
    - service: notify.telegramdepablo
      data:
        title: "Termostato:"
        message: |
          Se ha puesto la calefacción en modo ECO
          - Temperatura actual: {{ states.sensor.nest_thermostat_temperature.state }}°C
          - Temperatura exterior: {{ states.sensor.dark_sky_temperature.state }}°C