- platform: darksky
  api_key: !secret darksky_apikey
  update_interval: '00:04:30'
  units: ca
#  forecast:
#    - 1
#    - 2
#    - 3
#    - 4
#    - 5
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - ozone
    - moon_phase