- platform: template
  sensors:
    summary:
      friendly_name: Informe de situación
      value_template: >-
        Este es el informe de situación de la casa.
        {% if is_state('group.all_switches', 'on') %}
          Las siguientes luces están encendidas.
          {% for state in states.switch -%}
            {% if state.state == 'on' %}
              {{state.name}}.
            {% endif %}
          {%- endfor %}
        {%- else -%}
          No hay ninguna luz encendida.
        {%- endif -%}
        {{ states.sensor.heating_summary.state }}
#        {{ states.sensor.lights_summary.state }}{{- '\n' -}}
#        {{ states.sensor.heating_summary.state }}